### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by pawamoy** [m-col/m-col#1]
Hey @m-col, sorry for spamming here, just wanted to let you know that the payment on Liberapay might fail (it says it was successful, but I highly doubt it since the linked bank account is closed). I've set up my new bank account there. Anyway, I hope you're doing well and that you still enjoy using/hacking Qtile :smile: (still using it myself :slightly_smiling_face: )

**Comment by m-col** [comment]
Hey! no worries, and thanks again :) I hope you're well too. Still loving Qtile of course! Unfortunately I've been a little AFK the past couple months due to uni work but incidentally that ends this weekend so I'm now gonna be ramping up the hacking hard, and i'm pumped for it
